claroline/CoreBundle

Form/Badge/Type/BadgeRuleType.php
Resources/public/js/resourceinput.js

Add custom parameters that can be pass through the form field type `resourcePicker` to configure the picker the way we want.
In addition to picker parameters I add a parameter to allow to hide/display the download button on the picker.

Resource picker custom parameters

---

Controller/Administration/ParametersController.php
Form/Administration/IndexingType.php
Library/Configuration/PlatformConfiguration.php
Resources/translations/platform.en.yml
Resources/translations/platform.fr.yml
Resources/views/Administration/Parameters/appearanceForm.html.twig
Resources/views/Administration/Parameters/generalForm.html.twig
Resources/views/Administration/Parameters/index.html.twig

This PR fix https://github.com/claroline/Claroline/issues/644.
The regex for google meta validation wasn't good and make all parameters form not validating.

Improve admin parameters forms

---

Resources/translations/platform.fr.yml

Spelling mistakes in the french platform.yml translation file

Orthographe

---

DataFixtures/Required/Data/LoadWidgetData.php
Entity/Plugin.php
Entity/Widget/Widget.php
Library/Installation/Plugin/DatabaseWriter.php
Migrations/drizzle_pdo_mysql/Version20150224133221.php
Migrations/ibm_db2/Version20150224133221.php
Migrations/mysqli/Version20150224133221.php
Migrations/oci8/Version20150224133221.php
Migrations/pdo_mysql/Version20150224133221.php
Migrations/pdo_oci/Version20150224133221.php
Migrations/pdo_pgsql/Version20150224133221.php
Migrations/pdo_sqlite/Version20150224133221.php
Migrations/pdo_sqlsrv/Version20150224133221.php
Migrations/sqlanywhere/Version20150224133221.php
Migrations/sqlsrv/Version20150224133221.php

Remove plugin and widget icon

---

Library/Installation/Plugin/DatabaseWriter.php

Update admin tools when updating plugin

---

Command/Dev/TestUpdateCommand.php
Command/PlatformInstallCommand.php
Library/Installation/AdditionalInstaller.php
Library/Installation/OperationExecutor.php
Library/Installation/PlatformInstaller.php
Library/Installation/Plugin/Installer.php

Need this PR https://github.com/claroline/InstallationBundle/pull/4 before merge.

Refacto log feature for installation process

---

Library/Installation/Updater/Updater020000.php
Library/Installation/Updater/Updater020102.php
Library/Installation/Updater/Updater020200.php
Library/Installation/Updater/Updater020301.php
Library/Installation/Updater/Updater020304.php
Library/Installation/Updater/Updater020500.php
Library/Installation/Updater/Updater020800.php
Library/Installation/Updater/Updater020900.php
Library/Installation/Updater/Updater021000.php
Library/Installation/Updater/Updater021100.php
Library/Installation/Updater/Updater021200.php
Library/Installation/Updater/Updater021201.php
Library/Installation/Updater/Updater021400.php
Library/Installation/Updater/Updater021401.php
Library/Installation/Updater/Updater021600.php
Library/Installation/Updater/Updater021602.php
Library/Installation/Updater/Updater021604.php
Library/Installation/Updater/Updater030000.php
Library/Installation/Updater/Updater030100.php
Library/Installation/Updater/Updater030200.php
Library/Installation/Updater/Updater030300.php
Library/Installation/Updater/Updater030400.php
Library/Installation/Updater/Updater030502.php
Library/Installation/Updater/Updater030601.php
Library/Installation/Updater/Updater030700.php
Library/Installation/Updater/Updater030800.php
Library/Installation/Updater/Updater040100.php
Library/Installation/Updater/Updater040200.php

Need this PR https://github.com/claroline/InstallationBundle/pull/5 before merged.

Fix updater with newly created Updater base class from InstallationBundle

---

Library/Installation/Updater/Updater040500.php

Less time and memory taken to reorder a lot of resources.

Improve performance when reordering resources

---

Library/Installation/Updater/Updater040800.php
Manager/ToolManager.php

Fix bug and improve perf

---

Command/PlatformInstallCommand.php
Command/PlatformUpdateCommand.php

Just to know how long the command lasted.

Add time in output for long command

---

Library/Transfert/ConfigurationBuilders/Tools/ResourceManagerImporter.php

This PR will require some minor changes in WikiBundle and ExoBundle.

Add data key to data give to validate method

---

Entity/Resource/ResourceType.php
Event/Notification/NotificationUserParametersEvent.php
Library/Installation/Plugin/Configuration.php
Library/Installation/Plugin/DatabaseWriter.php
Listener/Notification/NotificationUserParametersListener.php
Manager/ResourceManager.php
Menu/Builder.php
Repository/ResourceTypeRepository.php
Resources/translations/notification.en.yml
Resources/translations/notification.es.yml
Resources/translations/notification.fr.yml

Replaced is_notifiable parameter in resource type with NotificationUserParametersListener for better plugin coverage (if for example plugin has no resource e.g. portfolioPlugin)

Replaced is_notifiable parameter with NotificationUserParametersListener

---

Controller/Administration/ParametersController.php
Form/Administration/AppearanceType.php
Form/Administration/FacebookType.php
Form/Administration/GeneralType.php
Form/Administration/IndexingType.php
Form/Administration/MailInscriptionType.php
Form/Administration/MailServerType.php
Form/Administration/SessionType.php
Form/Administration/TermsOfServiceType.php
Library/Configuration/PlatformConfigurationHandler.php
Resources/config/parameters.yml

Platform options can be locked by adding its key in app/config/locked_platform_options.yml

Lock platform options

---

composer.json

Update font awesome version

---

Resources/views/Layout/stylesheets.html.twig

Fixes 404 error from font-awesome.css.

Add support for font awesome's new woff2 format

---

Controller/ResourcePropertiesController.php
Form/Administration/GeneralType.php
Form/GroupSettingsType.php
Form/HomeTabType.php
Form/ImportUserType.php
Form/ProfileCreationType.php
Form/ProfileType.php
Form/ResourcePropertiesType.php
Form/WidgetInstanceType.php

- Restores translations in form entity fields (disabled as of Symfony 2.7)
- Fixes a DI config bug

Update entity fields for 2.7 + bug fix

---

Library/Installation/Updater/Updater050100.php

Fixes the errors related to the non-existence of the *files/templates* directory.

Fix updater

---

Manager/ResourceManager.php
Repository/ResourceNodeRepository.php
Repository/ResourceQueryBuilder.php
Resources/views/Tool/workspace/home/workspaceHomeLayout.html.twig
Resources/views/macros.html.twig

- Remove breadcrumbs for anonymous in workspace home page
- Fix ws resources access for anonymous

Fix anonymous workspace access

---

Resources/public/js/resource/manager/manager.js

add a method to delete the reference to a resource picker.

add destroy method

---

Controller/ResourceController.php
Event/ResourceCreatedEvent.php
Repository/RoleRepository.php
Resources/views/Workspace/layout.html.twig

- Generate an event when a resource is created
- Truncate breadcrumbs for anonymous in workspace

Resource created event + anonymous breadcrumbs

---

Entity/Workspace/Workspace.php
Resources/views/Workspace/layout.html.twig

In the blog I don't create workspace variable for my template and so I got error.
This PR fix this and clean a little bit.

Fix getting background color for workspace

---

Controller/Administration/AnalyticsController.php
Event/Analytics/PlatformContentItemDetailsEvent.php
Event/Analytics/PlatformContentItemEvent.php
Resources/translations/platform.en.yml
Resources/translations/platform.fr.yml
Resources/views/Administration/Analytics/analytics_navbar.html.twig
Resources/views/Administration/Analytics/analytics_resources.html.twig
Resources/views/Administration/Analytics/analytics_resources_item.html.twig
Resources/views/Log/resource_by_type_chart.html.twig

Allow plugin to add specific page for their resources in the platform content analystics page.

Analytics add plugin data

---

Entity/Resource/ResourceIcon.php

Can you create a new tag when this is merge please ?
This creates a bug in our fork of Dropzone when we try do delete an uploaded document.

Cascade the shortcut icon relation

---

Resources/translations/platform.de.yml
Resources/translations/platform.en.yml
Resources/translations/platform.es.yml
Resources/translations/platform.fr.yml
Resources/views/Form/date_range.html.twig

Need https://github.com/claroline/FrontEndBundle/pull/36 before it can be merged.

Update daterange-picker form field template and format

---

Form/Field/DateTimePickerType.php
Resources/views/Form/date_time_picker.html.twig

has already been merged in master but not in 5x apparently
thanks !

fix datepicker has-error condition

---

Library/Transfert/ConfigurationBuilders/Tools/Resources/ActivityImporter.php
Library/Transfert/RichTextFormatter.php
Listener/Transfer/ImgFormatListener.php

Can we have a tag for this fix please ? We are not able to export anything because of this.

fix bug in import/export when Activity has no parameters

---

Repository/UserRepository.php

FIX : Search users should not return disabled users

---

Resources/config/suggested/framework_test.yml

See http://symfony.com/blog/new-in-symfony-2-2-functional-tests-speed-up.

Disable profiler in test environment

---

Repository/ResourceQueryBuilder.php

I can't use the ResourceQueryBuilder and add custom WHERE clause to the queries that are generated.

Allow custom where from Repositories

---

Resources/public/js/tinymce/tinymce.js
Resources/views/Administration/Analytics/analytics.html.twig
Resources/views/Administration/Analytics/analytics_connections.html.twig
Resources/views/Administration/HomeTab/adminHomeTabsConfig.html.twig
Resources/views/Administration/Parameters/generalForm.html.twig
Resources/views/Exception/layout.html.twig
Resources/views/Form/date_range.html.twig
Resources/views/Form/simple_auto_complete.html.twig
Resources/views/Form/two_level_select.html.twig
Resources/views/Home/home.html.twig
Resources/views/Layout/javascripts.html.twig
Resources/views/Layout/javascripts_headers.html.twig
Resources/views/Layout/stylesheets.html.twig
Resources/views/Log/count_by_day_chart.html.twig
Resources/views/Log/resource_by_type_chart.html.twig
Resources/views/Log/view_user_list.html.twig
Resources/views/Theme/edit.html.twig
Resources/views/Tool/desktop/home/desktopHomeLayout.html.twig
Resources/views/Tool/desktop/parameters/userOptionsEditForm.html.twig
Resources/views/Tool/desktop/resource_manager/resources.html.twig
Resources/views/Tool/workspace/analytics/resources.html.twig
Resources/views/Tool/workspace/home/workspaceHomeLayout.html.twig
Resources/views/Tool/workspace/parameters/workspaceDisplayEditForm.html.twig
Resources/views/Tool/workspace/resource_manager/resources.html.twig
Resources/views/Widget/embed/widget.html.twig
Resources/views/layout.html.twig
composer.json

- depends on claroline/FrontEndBundle#42
- assumes the `angular-bower` branch is merged into master and a 6.1.0 tag is created 
- otherwise, good to merge

Update frontend assets paths (bower switch)

---

Repository/ResourceQueryBuilder.php

Extending the base Doctrine QueryBuilder is not possible without lots of changes in code, because queries are not generated the same way in the custom builder.

allow custom JOIN in ResourceQueries

---

Manager/LocaleManager.php

Allow default locale without session

---

Resources/views/Resource/listElement.html.twigjs

add missing slash to resource icon path in list view mode

---

Controller/FileController.php

Port of claroline/Distribution#169 on v5.

Avoid sending response twice and switch to binary file response
